name: Add Notice

on:
  workflow_call:
    inputs:
      message:
        type: string
  workflow_dispatch:

jobs:
  check-notice-existence:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: "Check file existence"
        id: check-files
        uses: andstor/file-existence-action@v3
        with:
          files: "NOTICE"

      - name: print-info - skip add-notice
        if: steps.check-files.outputs.files_exists
        run: echo "add-notice needs a ./NOTICE file"

    outputs:
      notice_exist: ${{ steps.check-files.outputs.files_exists }}

  add-notice:
    needs: check-notice-existence
    if: ${{ needs.check-notice-existence.outputs.notice_exist == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - run: git pull

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-attribution
        uses: taiki-e/install-action@v2
        with:
          tool: add-header

      - name: Run cargo attribution
        run: add-header

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[${{ inputs.message || 'Manual run' }}]: Add Notice to New Files"
