[[dependencies]]
name = "addr2line"
version = "0.21.0"
description = "A cross-platform symbolication library written in Rust, using `gimli`"
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2016-2018 The gimli Developers"]
repository = "https://github.com/gimli-rs/addr2line"

[[dependencies]]
name = "adler"
version = "1.0.2"
description = "A simple clean-room implementation of the Adler-32 checksum"
license = "0BSD OR MIT OR Apache-2.0"
notices = ["Copyright (C) Jonas Schievink <jonasschievink@gmail.com>"]
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
repository = "https://github.com/jonas-schievink/adler.git"

[[dependencies]]
name = "anstream"
version = "0.6.18"
description = "A simple cross platform library for writing colored text to a terminal."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/rust-cli/anstyle.git"
homepage = "https://github.com/rust-cli/anstyle"

[[dependencies]]
name = "anstyle"
version = "1.0.10"
description = "ANSI text styling"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2022 The rust-cli Developers"]
repository = "https://github.com/rust-cli/anstyle.git"
homepage = "https://github.com/rust-cli/anstyle"

[[dependencies]]
name = "anstyle-parse"
version = "0.2.6"
description = "Parse ANSI Style Escapes"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2016 Joe Wilm and individual contributors"]
repository = "https://github.com/rust-cli/anstyle.git"
homepage = "https://github.com/rust-cli/anstyle"

[[dependencies]]
name = "anstyle-query"
version = "1.1.2"
description = "Look up colored console capabilities"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/rust-cli/anstyle.git"

[[dependencies]]
name = "anstyle-wincon"
version = "3.0.7"
description = "Styling legacy Windows terminals"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015 Josh Triplett, 2022 The rust-cli Developers"]
repository = "https://github.com/rust-cli/anstyle.git"
homepage = "https://github.com/rust-cli/anstyle"

[[dependencies]]
name = "backtrace"
version = "0.3.71"
description = """
A library to acquire a stack trace (backtrace) at runtime in a Rust program.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The Rust Project Developers"]
repository = "https://github.com/rust-lang/backtrace-rs"

[[dependencies]]
name = "cc"
version = "1.2.16"
description = """
A build-time dependency for Cargo build scripts to assist in invoking the native
C compiler to compile native C code into a static archive to be linked into Rust
code.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
repository = "https://github.com/rust-lang/cc-rs"

[[dependencies]]
name = "cfg-if"
version = "1.0.0"
description = """
A macro to ergonomically define an item depending on a large number of #[cfg]
parameters. Structured like an if-else chain, the first matching branch is the
item that gets emitted.
"""
license = "MIT/Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
repository = "https://github.com/alexcrichton/cfg-if"

[[dependencies]]
name = "clap"
version = "4.5.31"
description = "A simple to use, efficient, and full-featured Command Line Argument Parser"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/clap-rs/clap"

[[dependencies]]
name = "clap_builder"
version = "4.5.31"
description = "A simple to use, efficient, and full-featured Command Line Argument Parser"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015-2022 Kevin B. Knapp and Clap Contributors"]
repository = "https://github.com/clap-rs/clap"

[[dependencies]]
name = "clap_derive"
version = "4.5.28"
description = "Parse command line argument by defining a struct, derive crate."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015-2022 Kevin B. Knapp and Clap Contributors"]
repository = "https://github.com/clap-rs/clap"

[[dependencies]]
name = "clap_lex"
version = "0.7.4"
description = "Minimal, flexible command line parser"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015-2022 Kevin B. Knapp and Clap Contributors"]
repository = "https://github.com/clap-rs/clap"

[[dependencies]]
name = "color-eyre"
version = "0.6.3"
description = "An error report handler for panics and eyre::Reports for colorful, consistent, and well formatted error reports for all kinds of errors."
license = "MIT OR Apache-2.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
repository = "https://github.com/eyre-rs/eyre"

[[dependencies]]
name = "colorchoice"
version = "1.0.3"
description = "Global override of color control"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/rust-cli/anstyle.git"

[[dependencies]]
name = "eyre"
version = "0.6.12"
description = "Flexible concrete Error Reporting type built on std::error::Error with customizable Reports"
license = "MIT OR Apache-2.0"
authors = [
  "David Tolnay <dtolnay@gmail.com>",
  "Jane Lusby <jlusby42@gmail.com>",
]
repository = "https://github.com/eyre-rs/eyre"

[[dependencies]]
name = "gimli"
version = "0.28.1"
description = "A library for reading and writing the DWARF debugging format."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015 The Rust Project Developers"]
repository = "https://github.com/gimli-rs/gimli"

[[dependencies]]
name = "heck"
version = "0.5.0"
description = "heck is a case conversion library."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015 The Rust Project Developers"]
repository = "https://github.com/withoutboats/heck"

[[dependencies]]
name = "indenter"
version = "0.3.3"
description = """
A formatter wrapper that indents the text, designed for error display impls
"""
license = "MIT OR Apache-2.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
repository = "https://github.com/yaahc/indenter"

[[dependencies]]
name = "is_terminal_polyfill"
version = "1.70.1"
description = "Polyfill for `is_terminal` stdlib feature for use with older MSRVs"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/polyfill-rs/is_terminal_polyfill"

[[dependencies]]
name = "libc"
version = "0.2.170"
description = """
Raw FFI bindings to platform libraries like libc.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014-2020 The Rust Project Developers"]
authors = ["The Rust Project Developers"]
repository = "https://github.com/rust-lang/libc"

[[dependencies]]
name = "memchr"
version = "2.7.4"
description = """
Provides extremely fast (uses SIMD on x86_64, aarch64 and wasm32) routines for
1, 2 or 3 byte search and single substring search.
"""
license = "Unlicense OR MIT"
notices = ["Copyright (c) 2015 Andrew Gallant"]
authors = ["Andrew Gallant <jamslam@gmail.com>", "bluss"]
repository = "https://github.com/BurntSushi/memchr"

[[dependencies]]
name = "miniz_oxide"
version = "0.7.4"
description = "DEFLATE compression and decompression library rewritten in Rust based on miniz"
license = "MIT OR Zlib OR Apache-2.0"
notices = ["Copyright (c) 2017 Frommi", "Copyright (c) 2020 Frommi"]
authors = [
  "Frommi <daniil.liferenko@gmail.com>",
  "oyvindln <oyvindln@users.noreply.github.com>",
]
repository = "https://github.com/Frommi/miniz_oxide/tree/master/miniz_oxide"

[[dependencies]]
name = "object"
version = "0.32.2"
description = "A unified interface for reading and writing object file formats."
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2015 The Gimli Developers"]
repository = "https://github.com/gimli-rs/object"

[[dependencies]]
name = "once_cell"
version = "1.20.3"
description = "Single assignment cells and lazy values."
license = "MIT OR Apache-2.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/once_cell"

[[dependencies]]
name = "owo-colors"
version = "3.5.0"
description = "Zero-allocation terminal colors that'll make people go owo"
license = "MIT"
notices = ["Copyright (c) 2020 - present The owo-colors Developers"]
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
repository = "https://github.com/jam1garner/owo-colors"

[[dependencies]]
name = "proc-macro2"
version = "1.0.93"
description = "A substitute implementation of the compiler's `proc_macro` API to decouple token-based libraries from the procedural macro use case."
license = "MIT OR Apache-2.0"
authors = [
  "David Tolnay <dtolnay@gmail.com>",
  "Alex Crichton <alex@alexcrichton.com>",
]
repository = "https://github.com/dtolnay/proc-macro2"

[[dependencies]]
name = "quote"
version = "1.0.38"
description = "Quasi-quoting macro quote!(...)"
license = "MIT OR Apache-2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/quote"

[[dependencies]]
name = "rustc-demangle"
version = "0.1.24"
description = """
Rust compiler symbol demangling.
"""
license = "MIT/Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
repository = "https://github.com/rust-lang/rustc-demangle"

[[dependencies]]
name = "same-file"
version = "1.0.6"
description = """
A simple crate for determining whether two file paths point to the same file.
"""
license = "Unlicense/MIT"
notices = ["Copyright (c) 2017 Andrew Gallant"]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
repository = "https://github.com/BurntSushi/same-file"

[[dependencies]]
name = "shlex"
version = "1.3.0"
description = "Split a string into shell words, like Python's shlex."
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2015 Nicholas Allegra (comex).",
  "Copyright 2015 Nicholas Allegra (comex).",
]
authors = [
  "comex <comexk@gmail.com>",
  "Fenhl <fenhl@fenhl.net>",
  "Adrian Taylor <adetaylor@chromium.org>",
  "Alex Touchet <alextouchet@outlook.com>",
  "Daniel Parks <dp+git@oxidized.org>",
  "Garrett Berg <googberg@gmail.com>",
]
repository = "https://github.com/comex/rust-shlex"

[[dependencies]]
name = "strsim"
version = "0.11.1"
description = """
Implementations of string similarity metrics. Includes Hamming, Levenshtein,
OSA, Damerau-Levenshtein, Jaro, Jaro-Winkler, and Sørensen-Dice.
"""
license = "MIT"
notices = [
  "Copyright (c) 2015 Danny Guo",
  "Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>",
  "Copyright (c) 2018 Akash Kurdekar",
]
authors = ["Danny Guo <danny@dannyguo.com>", "maxbachmann <oss@maxbachmann.de>"]
repository = "https://github.com/rapidfuzz/strsim-rs"

[[dependencies]]
name = "syn"
version = "2.0.98"
description = "Parser for Rust source code"
license = "MIT OR Apache-2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/syn"

[[dependencies]]
name = "unicode-ident"
version = "1.0.17"
description = "Determine whether characters have the XID_Start or XID_Continue properties according to Unicode Standard Annex #31"
license = "(MIT OR Apache-2.0) AND Unicode-3.0"
notices = ["Copyright © 1991-2023 Unicode, Inc."]
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/unicode-ident"

[[dependencies]]
name = "utf8parse"
version = "0.2.2"
description = "Table-driven UTF-8 parser"
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2016 Joe Wilm"]
authors = [
  "Joe Wilm <joe@jwilm.com>",
  "Christian Duerr <contact@christianduerr.com>",
]
repository = "https://github.com/alacritty/vte"

[[dependencies]]
name = "walkdir"
version = "2.5.0"
description = "Recursively walk a directory."
license = "Unlicense/MIT"
notices = ["Copyright (c) 2015 Andrew Gallant"]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
repository = "https://github.com/BurntSushi/walkdir"

[[dependencies]]
name = "winapi-util"
version = "0.1.9"
description = "A dumping ground for high level safe wrappers over windows-sys."
license = "Unlicense OR MIT"
notices = ["Copyright (c) 2017 Andrew Gallant"]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
repository = "https://github.com/BurntSushi/winapi-util"

[[dependencies]]
name = "windows-sys"
version = "0.59.0"
description = "Rust for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows-targets"
version = "0.52.6"
description = "Import libs for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows_aarch64_gnullvm"
version = "0.52.6"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows_aarch64_msvc"
version = "0.52.6"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows_i686_gnu"
version = "0.52.6"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows_i686_gnullvm"
version = "0.52.6"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows_i686_msvc"
version = "0.52.6"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows_x86_64_gnu"
version = "0.52.6"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows_x86_64_gnullvm"
version = "0.52.6"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependencies]]
name = "windows_x86_64_msvc"
version = "0.52.6"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"
